### ISSUE TITLE
Support for Material UI 0.15

### ISSUE THREAD

**Issue by ghost** [lynndylanhurley/redux-auth-demo#6]
Hi there, 

Great library but I'm getting these errors when running it against the latest Material UI build (v. 0.15.0+). 

`
Error: Cannot resolve module 'material-ui/lib/svg-icons' in /../node_modules/redux-auth
 @ ./~/redux-auth/material-ui-theme.js
`
`
Error: Cannot resolve module 'material-ui/lib/styles/colors' in /../node_modules/redux-auth
 @ ./~/redux-auth/material-ui-theme.js
`

Looks like the latest MaterialUI 0.15.0+ introduced a breaking change on how to reference MaterialUI components. Please see more details in their [change log](https://github.com/callemall/material-ui/blob/master/CHANGELOG.md).

**Comment by Sigiller** [comment]
+1

**Comment by lynndylanhurley** [comment]
Done
