### ISSUE TITLE
Issue with Github OAuth

### ISSUE THREAD

**Issue by triandicAnt** [lynndylanhurley/redux-auth-demo#8]
Hello,

I am trying to use Github OAuth but the oAuth Pop up window is showing up "Server not found" page.

![github](https://cloud.githubusercontent.com/assets/2345902/20400959/e684536a-acc4-11e6-817d-302c2e37a741.png)

Am I missing something!

**Comment by triandicAnt** [comment]
My fault... the auth token and secret key had not provided...

**Comment by himanshu0128** [comment]
how did you supply the auth token and the secret key?

**Comment by triandicAnt** [comment]
@decentname You can following steps mentioned in the following link : 
https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

**Comment by himanshu0128** [comment]
I have this token but are we not supposed to supply client id and client secret for Oauth in the demo? I am not able to use the demo.
